//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_db
    {
        public int id { get; set; }
        public string currency { get; set; }
        public int salary_id { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> salaryAmount { get; set; }
    
        public virtual userinfo_db userinfo_db { get; set; }
    }
}
